// Code generated by @furo/ui-builder. DO NOT EDIT.
import { LitElement, html, css } from 'lit-element';
import { Theme } from '@furo/framework/src/theme.js';
import { FBP } from '@furo/fbp';

// eslint-disable-next-line no-unused-vars
import { i18n } from '@furo/framework/src/i18n.js';

import '@furo/data-input';
import '@furo/form';

/**
 * Defines a field in the furo spec
 *
 * @summary todo: write summary
 * @customElement
 * @polymer
 * @appliesMixin FBP
 */
export class StringRepeat extends FBP(LitElement) {
  constructor() {
    super();
    this.field = {};
    this.labelAdd = 'add item';
    this.emptyString = '';
  }

  /**
   * @private
   * @return {Object}
   */
  static get properties() {
    return {
      // Header text
      headerText: {
        type: String,
        attribute: 'header-text',
      },
      // Secondary text
      secondaryText: {
        type: String,
        attribute: 'secondary-text',
      },
      // Label for the add button
      labelAdd: {
        type: String,
        attribute: 'label-add-button',
      },
    };
  }

  // Fokus
  focus(d) {
    this._FBPTriggerWire('--focused', d);
  }

  /**
   * flow is ready lifecycle method
   */
  _FBPReady() {
    super._FBPReady();
    //  this._FBPTraceWires()
  }

  /**
   *  Bind your furo-data-object event @-object-ready
   * @public
   * @param data
   */
  bindData(data) {
    this._FBPTriggerWire('--data', data);
    this.field = data;
    this.requestUpdate();
  }

  /**
   * Themable Styles
   * @private
   * @return {CSSResult}
   */
  static get styles() {
    // language=CSS
    return (
      Theme.getThemeForComponent('RepeatBaseTheme') ||
      css`
        :host {
          display: block;
        }

        :host[hidden] {
          display: none;
        }

        furo-button {
          margin: 12px 0 0 6px;
        }

        furo-horizontal-flex {
          margin-bottom: 6px;
        }
      `
    );
  }

  /**
   * @private
   * @returns {TemplateResult}
   * @private
   */
  render() {
    // language=HTML
    return html`
      <!-- It is a good practice to set a description -->
      <furo-form
        header-text="${this.headerText}"
        secondary-text="${this.secondaryText}"
      ></furo-form>

      <!-- We repeat the fields -->
      <furo-data-repeat
        delete-icon="delete"
        condensed
        repeated-component="furo-data-text-input"
        ƒ-bind-data="--data"
        ƒ-add="--adderTriggered"
        focus-on-create
      ></furo-data-repeat>

      <!-- We flex with a empty div[flex] to align the button on the right -->
      <furo-horizontal-flex>
        <div flex></div>
        <!-- Clicking the button will trigger --adderTriggered end send the value from this.emptyString.
             Otherwise the click will send us the value 1  -->
        <furo-button label="${this.labelAdd}" @-click="--adderTriggered(emptyString)"></furo-button>
      </furo-horizontal-flex>
    `;
  }
}

window.customElements.define('string-repeat', StringRepeat);
